// The app's icon vocabulary — one curated set, consistent stroke, no emojis.
// Use size 18–20 in buttons/rows, 14 inside chips/badges.
export {
  Camera,
  Check,
  ChevronLeft,
  Clock,
  Copy,
  Download,
  Share,
  SquarePlus,
  ExternalLink,
  Eye,
  Globe,
  EyeOff,
  History,
  House,
  ImageDown,
  ImageUp,
  Info,
  PencilLine,
  Plus,
  QrCode,
  Settings,
  Share2,
  Trash2,
  Undo2,
  UserPlus,
  X,
} from 'lucide-react'
